/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tareas;

import java.io.File;
import javax.swing.DefaultListModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author eduardo
 */
public class ListaTareas extends javax.swing.JFrame {
    
    /**
     * Creates new form ListaTareas
     */
    public ListaTareas() {
        initComponents();
        Date fecha = new Date(System.currentTimeMillis());
        //System.out.println(fecha);
        SimpleDateFormat sf= new SimpleDateFormat("dd-MM-yyyy");
        System.out.println(sf.format(fecha));
        
        try {
            File db=new File("tareas.bd");
            Class.forName("org.sqlite.JDBC");
            co=DriverManager.getConnection("jdbc:sqlite:"+db.getAbsolutePath());
        } catch (Exception e) {
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnAñadirTarea = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTareas = new javax.swing.JList<>();
        txtTitulo = new javax.swing.JTextField();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        TITULO = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        btnAñadirTarea.setText("AÑADIR TAREA");
        btnAñadirTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirTareaActionPerformed(evt);
            }
        });

        lstTareas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTareasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstTareas);

        txtFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFechaPropertyChange(evt);
            }
        });

        jLabel1.setText("FECHA");

        TITULO.setText("TITULO");

        jLabel2.setText("DESCRIPCION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TITULO)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAñadirTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TITULO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAñadirTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirTareaActionPerformed
        // TODO add your handling code here:
         sentencia  = "insert into tarea(titulo, descripcion, fecha, status) values(?,?,?,?)";
         String fecha=txtFecha.getDateFormatString(),
               titulo=txtTitulo.getText(),
               descripcion=txtDescripcion.getText();
        int status=0;
        try {    
            PreparedStatement ps = co.prepareStatement(sentencia);
            ps.setString(1,titulo);
            ps.setString(2,descripcion);
            ps.setString(3,fecha);
            ps.setInt(4,status);
            int i = ps.executeUpdate();
            if (i!=0) {
                javax.swing.JOptionPane.showInternalMessageDialog(null, "Tarea creada con exito");
                listarTareas();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        //dlm.addElement("hola mundo");
    }//GEN-LAST:event_btnAñadirTareaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listarTareas();
    }//GEN-LAST:event_formWindowOpened

    private void lstTareasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTareasMouseClicked
        String opcion []={"cancelar","en proceso","terminado"};
        String num=lstTareas.getSelectedValue().split("--")[0];
        
        if (evt.getClickCount()==2) {
            int opcionSeleccionada = javax.swing.JOptionPane.showOptionDialog(null,"Hacia que estado decea mover la tarea:","tarea n°:"+num, javax.swing.JOptionPane.DEFAULT_OPTION,javax.swing.JOptionPane.INFORMATION_MESSAGE,null, opcion, null);
            
            switch (opcionSeleccionada) {
                
                case 1:
                    javax.swing.JOptionPane.showInternalMessageDialog(null, "estatus camiado");
                break;
                
                case 2:
                    javax.swing.JOptionPane.showInternalMessageDialog(null, "tarea terminada");
                break;
                
            }
        }
    }//GEN-LAST:event_lstTareasMouseClicked
    int i;
    private void txtFechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFechaPropertyChange
        //if(evt.getPropertyName().compareTo("day")==0){
            System.out.println("se ha cambiado la fecha"+i++);
        //}
    }//GEN-LAST:event_txtFechaPropertyChange
    private void listarTareas(){
        dlm = new DefaultListModel();
        lstTareas.setModel(dlm);
        
        sentencia="select (id, titulo) from tarea";
        try {
            st=co.createStatement();
            rs = st.executeQuery(sentencia);
            while (rs.next()) {
                dlm.addElement(rs.getString("id")+"--"+rs.getString("titulo"));
                
            }
        } catch (Exception e) {
        }
    }
    
    private void fitrarPorFecha(){
        sentencia="select (id, titulo) from tarea  ";
        try {
            st=co.createStatement();
            rs = st.executeQuery(sentencia);
            while (rs.next()) {
                dlm.addElement(rs.getString("id")+"--"+rs.getString("titulo"));
                
            }
        } catch (Exception e) {
        }
    }
    public void fecha(Object fecha2){
        Date fecha = new Date(System.currentTimeMillis());
        SimpleDateFormat sf= new SimpleDateFormat("dd-MM-yyyy");
        //System.out.println(fecha);
        System.out.println(sf.format(fecha));   
        
       
    }
    private String sentencia;
    private Connection co;
    private Statement st;
    private ResultSet rs;
    private DefaultListModel dlm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TITULO;
    private javax.swing.JButton btnAñadirTarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstTareas;
    private javax.swing.JTextArea txtDescripcion;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
